micronaut:
    application:
        name: events-api
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
    executors:
        scheduled:
            type: scheduled
            core-pool-size: 30
    security:
        enabled: true
        endpoints:
            login:
                enabled: true
            oauth:
                enabled: true
        intercept-url-map:
            -
              pattern: /swagger/*
              http-method: GET
              access:
                    - isAnonymous()
            -
              pattern: /api/v1/account/register
              http-method: POST
              access:
                  - isAnonymous()
        token:
            jwt:
                enabled: true
                signatures:
                    secret:
                        generator:
                            secret: pleaseChangeThisSecretForANewOne